# brew "awscli"
brew "bash"
brew "chafa"
# brew "clojure"
# brew "clojure-lsp"
brew "entr"
brew "fennel"
brew "fish"
brew "git"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
brew "htop"
brew "idris"
brew "imagemagick"
# brew "leiningen"
brew "libpq"
brew "libxml2"
brew "libxslt"
brew "luarocks"
brew "mplayer"
brew "ncdu"
brew "neovim"
# brew "nim"
# brew "pyenv" 
brew "reattach-to-user-namespace"
brew "rename"
brew "stow"
brew "tmux"
# brew "tree"
brew "universal-ctags"
