# brew "awscli"
brew "ast-grep"
brew "aws-iam-authenticator"
brew "bash"
brew "bat"
brew "ccls"
brew "chafa"
# brew "clojure"
# brew "clojure-lsp"
# brew "elixir"
# brew "elixir-ls"
# brew "erlang"
brew "entr"
brew "eza"
brew "fd"
brew "fennel"
brew "fish"
brew "fnlfmt"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
# brew "gleam"
brew "htop"
brew "idris"
brew "imagemagick"
brew "jq"
brew "leiningen"
# brew "lf"
brew "libpq"
brew "libxml2"
brew "libxslt"
# lua-language-server -> mise (aqua:LuaLS/lua-language-server)
brew "luarocks"
# mise itself is installed via mise.run in setup.sh (both OSes), not brew
brew "mplayer"
brew "ncdu"
brew "neovim"
# brew "nim"
# brew "node"
# brew "opam"
# brew "pyenv" 
# brew "python" 
brew "reattach-to-user-namespace"
brew "rename"
# brew "ripgrep"
# brew "rust-analyzer"
brew "sops"
# brew "starship"
brew "stow"
brew "tmux"
# brew "tree"
brew "universal-ctags"
brew "uv"
# yaml-language-server -> mise (npm:yaml-language-server)
brew "zoxide"
