# brew "awscli"
brew "ast-grep"
brew "aws-iam-authenticator"
brew "bash"
brew "bat"
brew "ccls"
brew "chafa"
# brew "clojure"
# brew "clojure-lsp"
brew "entr"
brew "eza"
brew "fd"
brew "fennel"
brew "fish"
brew "fnlfmt"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
brew "htop"
brew "idris"
brew "imagemagick"
brew "jq"
# brew "leiningen"
brew "libpq"
brew "libxml2"
brew "libxslt"
brew "luarocks"
brew "mplayer"
brew "ncdu"
brew "neovim"
# brew "nim"
# brew "pyenv" 
brew "reattach-to-user-namespace"
brew "rename"
brew "ripgrep"
brew "sops"
brew "stow"
brew "tmux"
# brew "tree"
brew "universal-ctags"
brew "uv"
brew "zoxide"
