[tool.ruff]
line-length = 88
extend-exclude = ["**/settings/*", "**/snapshots/*", "**/migrations/*"]

[tool.ruff.format]
preview = true
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint]
preview = true
select = [
    "E", "W", # pycodestyle
    "F", # pyflakes
    "UP", # pyupgrade
    "I", # isort
    "C", # mccabe
    # flake8-bugbear
    "B",
    # flake8-simplify
    # "SIM",
    # "D", # pydocstyle
]
ignore = ["E203", "E266", "D100", "SIM108"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
