command_timeout = 1000

# [character]
# success_symbol = '[ﯟ](bold green)' 

[aws]
disabled = true

[cmd_duration]
disabled = true

[python]
pyenv_version_name = true
format = '[(\($virtualenv\) )]($style)'
